/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/auth`; params?: Router.UnknownInputParams; } | { pathname: `/driver-home`; params?: Router.UnknownInputParams; } | { pathname: `/driver-map`; params?: Router.UnknownInputParams; } | { pathname: `/driver-onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/driver-route-selection`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/otp`; params?: Router.UnknownInputParams; } | { pathname: `/rider-onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/route-selection`; params?: Router.UnknownInputParams; } | { pathname: `/user-type`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/map` | `/map`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/auth`; params?: Router.UnknownOutputParams; } | { pathname: `/driver-home`; params?: Router.UnknownOutputParams; } | { pathname: `/driver-map`; params?: Router.UnknownOutputParams; } | { pathname: `/driver-onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/driver-route-selection`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/otp`; params?: Router.UnknownOutputParams; } | { pathname: `/rider-onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/route-selection`; params?: Router.UnknownOutputParams; } | { pathname: `/user-type`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/map` | `/map`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/auth${`?${string}` | `#${string}` | ''}` | `/driver-home${`?${string}` | `#${string}` | ''}` | `/driver-map${`?${string}` | `#${string}` | ''}` | `/driver-onboarding${`?${string}` | `#${string}` | ''}` | `/driver-route-selection${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/otp${`?${string}` | `#${string}` | ''}` | `/rider-onboarding${`?${string}` | `#${string}` | ''}` | `/route-selection${`?${string}` | `#${string}` | ''}` | `/user-type${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/map${`?${string}` | `#${string}` | ''}` | `/map${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/auth`; params?: Router.UnknownInputParams; } | { pathname: `/driver-home`; params?: Router.UnknownInputParams; } | { pathname: `/driver-map`; params?: Router.UnknownInputParams; } | { pathname: `/driver-onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/driver-route-selection`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/otp`; params?: Router.UnknownInputParams; } | { pathname: `/rider-onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/route-selection`; params?: Router.UnknownInputParams; } | { pathname: `/user-type`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/map` | `/map`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
